swagger: "2.0"
info:
  description: "go-api interactive documentation"
  version: "1.0.0"
  title: "go-api"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "{{url}}"
basePath: "/v1"
tags:
- name: "image"
  description: "Everything about your Images"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /images:
    post:
      tags:
      - "image"
      summary: "Add a new image"
      description: ""
      operationId: "addImage"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Image object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Image"
      responses:
        400:
          description: "Invalid input"
        405:
          description: "Invalid input"
    put:
      tags:
      - "image"
      summary: "Update an existing image"
      description: ""
      operationId: "updateImage"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Image object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Image"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Image not found"
        405:
          description: "Validation exception"
          /image/{imageId}:
    get:
      tags:
      - "image"
      summary: "Get all images"
      description: "Return all images"
      operationId: "getImages"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Image"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Image not found"
  /image/{imageId}:
    get:
      tags:
      - "image"
      summary: "Find image by ID"
      description: "Returns a single image"
      operationId: "getImageById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of image to return"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Image"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Image not found"

definitions:
  Image:
    type: "object"
    required:
    - "id"
    - "title"
    - "slug"
    properties:
      id:
        type: "integer"
        format: "string"
      title:
        type: "string"
        example: "My image title"
      slug:
        type: "string"
        example: "My image slug"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
